#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing button listener...\n"
sudo cp listen-for-shutdown.py /usr/local/bin/
sudo chmod +x /usr/local/bin/listen-for-button.py

echo "=> Starting button listener...\n"
sudo cp listen-for-shutdown.sh /etc/init.d/
sudo chmod +x /etc/init.d/listen-for-button.sh

sudo update-rc.d listen-for-button.sh defaults
sudo /etc/init.d/listen-for-button.sh start

echo "Button listener installed.\n"