#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping button listener...\n"
sudo update-rc.d listen-for-button.sh remove
sudo /etc/init.d/listen-for-button.sh stop

echo "=> Removing button listener...\n"
sudo rm -rf /usr/local/bin/listen-for-button.py 
sudo rm -rf /etc/init.d/listen-for-button.sh 

echo "Button listener uninstalled.\n"
